#!/bin/bash
#
# To prevent debug code from being accidentally committed, simply add a comment near your
# debug code containing the keyword !nocommit and this script will abort the commit.
#
if git commit -v --dry-run | grep '!nocommit' >/dev/null 2>&1
then
  echo "[pre-commit] Trying to commit non-committable code."
  echo "[pre-commit] Remove the !nocommit string and try again."
  exit 1
else
  exit 0
fi
